### ISSUE TITLE
use vector::emplace_back more effectively

### ISSUE THREAD

**Issue by yumetodo** [antlarr/bard#3]
in https://github.com/antlarr/bard/commit/52bce48eca635f6210036366759ecd9c27ea0924 , `std::vector<std::pair<int,std::vector<int>>>` was introduced.

However, as far as I know, you can use `vector::emplace_back` more effectively.

```diff
--- current
+++ propose
- m_fingerprints.emplace_back(std::make_pair(songID, v));
+ m_fingerprints.emplace_back(songID, std::move(v));
```

- construct std::pair on new element append for readability(performance will be same due to RVO)
- **move vector to avoid copy**

**Comment by antlarr** [comment]
Thanks for the suggestion! I already applied the changes. I don't think it has a measurable improvement since it's only done once per song added to the fingerprints' vector, but any optimization is welcomed :)
